version: "3"
services:
  fpm:
    image: php:7.2.4-fpm-alpine
    container_name: fpm
    volumes:
      - /docker/web5/www:/var/www/html
    networks:
      myweb:
        ipv4_address: 192.100.0.3
  nginx:
    image: nginx:1.15.6-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /docker/web5/www:/usr/share/nginx/html/
      - /docker/web5/conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      myweb:
        ipv4_address: 192.100.0.2
networks:
  myweb:
    driver: bridge
    ipam:
      config:
        - subnet: 192.100.0.0/16